# Use root/example as user/password credentials
version: "3.1"

services:
  app:
    build: .
    environment:
      TELEGRAM_BOT_KEY: # Colocar aqui a key do bot do telegram
      BRASIL_API_URL: https://brasilapi.com.br/api
    restart: on-failure
