# Use root/example as user/password credentials
version: "3.1"

services:
  app:
    build: .
    environment:
      TELEGRAM_BOT_KEY: 5239154159:AAFcbgaQEGlHmprYf2Lb7XAu-bigK7E3y5E # Colocar aqui a key do bot do telegram
      BRASIL_API_URL: https://brasilapi.com.br/api
    restart: on-failure
